version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"  # Root of your project
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"  # For GitHub Actions in .github/workflows
    schedule:
      interval: "weekly"

