# .github/workflows/deploy.yml

name: Deploy to AWS

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Static Site
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: kjellhysjulien.com
      CLOUDFRONT_DISTRIBUTION_ID: E1M6WG52DZEBP1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::843785657965:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync files to S3
        run: aws s3 sync ./site/ s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"

